### PR TITLE
Update Readme.md typo-fixed

### PR DESCRIPTION
**Pull request by ysfcndgr**
Fixed typo in readme file.

### CODE REVIEW

**Comment by chanc8914-ux** [comment]
Add me

**Comment by ef106** [comment]
Tnkx

**Comment by Becktak** [comment]
thanks

**Comment by vediizzi** [comment]
good job

**Comment by ysfcndgr** [comment]
@ibaxio 
@scottafk 
@powerpook

**Comment by ysfcndgr** [comment]
> Fixed typo in readme file.

@ibaxio
@scottafk
@powerpook

**Comment by kurdoglu24** [comment]
thanks

**Comment by jerdal0909** [comment]
Thanks to you, I got scammed. I don't believe you.
I did not get 5000-500-200 retweets points. You are a liar

**Comment by Ishlah86** [comment]
god

**Comment by Annnaaq** [comment]
Thanks

**Pull request merged**
