### PR TITLE
merhabaCreate test

### PR DESCRIPTION
**Pull request by 8nokta2**
herkese bol kazançlar dilerim

### CODE REVIEW

**Comment by hrnrsln** [comment]
no problem

**Comment by Endercevrin** [comment]
Nice project

**Comment by Jacopblack** [comment]
Test

**Comment by Efsane4167** [comment]
Arkadaslar bos tartisma konusu acmayalim benxe

**Comment by Z2Y1T** [comment]
How many dollars do you think it would be?

**Pull request closed without merging**
