### PR TITLE
star eren

### PR DESCRIPTION
**Pull request by TaYRoN99**
An innovative Blockchain Protocol Platform, which everyone can deploy their own applications quickly and easily, such as Dapp, DeFi, DAO, Cross-Blockchain transactions, etc.

### CODE REVIEW

**Comment by ibrahimclskn66** [comment]
👏

**Comment by barlingoo** [comment]
👏

**Comment by metehanguler34** [comment]
When

**Comment by Ozgul1990** [comment]
🥳

**Pull request closed without merging**
