### PR TITLE
Create mel2

### PR DESCRIPTION
**Pull request by melisgln**
ee

### CODE REVIEW

**Comment by Welatsenn** [comment]
Nasıl olacak bu

**Comment by Sushant786786** [comment]
Ggg

**Comment by Jayanta2013** [comment]
Very nice project

**Comment by Fest0518** [comment]
3rr

**Comment by Gazarta** [comment]
Hhg

**Comment by IHCMATH** [comment]
yes

**Comment by ozd42** [comment]
nöğürecen

**Comment by ZagorKahraman** [comment]
Proof-of-work (PoW) is an economical measure to prevent denial-of-service attacks and abuse of services with spam messages on a network by asking the client to do some work (usually means the computer takes a certain amount of time). This concept was first introduced by Cynthia Dwork and Moni Naor in a 1993 journal article.[1] The term "Proof of Labor" or POW was first formalized by Markus Jakobsson and Ari Juels in a 1999 publication.[2] One of the first examples where the proof of labor system was used to add value to a currency was the shell money used in the Solomon Islands.

**Comment by ZagorKahraman** [comment]
The supply chain financial services platform digitally upgrades core businesses' accounts receivable, allowing accounts receivable to flow through the supply chain to upstream suppliers as credit credentials, solving the problem of expensive financing and difficult financing for small and medium businesses. Micro businesses at the end of the supply chain. At the same time, financial-grade identity security and transaction security authentication also provide a complete solution for businesses' online zero-contact transactions.

**Comment by ZagorKahraman** [comment]
Fully open to a variety of financial institutions such as banks, factoring, warranties and trusts, as well as core companies and suppliers upstream and downstream in the supply chain. Build a blockchain-based supply chain finance collaborative eco-system together. We also welcome large banks with strength to join the blockchain alliance to work together. The uploading, generation, flow, financing and destruction of digital assets for the whole life cycle of accounts receivable are done directly on the chain. Eliminate the double spending and reconciliation problems commonly occurred in non-blockchain systems.

**Comment by ZagorKahraman** [comment]
Open And Flow

Core companies can confirm and upload their accounts payable to first-tier suppliers online based on bank credit. Tier 1 suppliers can transfer their receivables to Tier 2 or more suppliers on the blockchain.

**Comment by ZagorKahraman** [comment]
Very cool in son heşep coin

**Comment by ZagorKahraman** [comment]
Open And Flow

Core companies can confirm and upload their accounts payable to first-tier suppliers online based on bank credit. Tier 1 suppliers can transfer their receivables to Tier 2 or more suppliers on the blockchain.

Get Started

**Comment by jerdal0909** [comment]
Thanks to you, I got scammed. I don't believe you.
I did not get 5000-500-200 retweets points. You are a liar

**Comment by jerdal0909** [comment]
Thanks to you, I got scammed. I don't believe you.
I did not get 5000-500-200 retweets points. You are a liar

**Pull request closed without merging**
